import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import { Slide, ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/authContext";
import { CartProvider } from "@/context/cartContext";
import GlobalHooks from "@/components/layout/global-hooks";
import RoutesPrivacy from "@/hook/useRoutesPrivacy/routes-privacy";



const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className="font-sans">
        <AuthProvider>
          <CartProvider>
            <RoutesPrivacy>
          {children}
           </RoutesPrivacy>
          </CartProvider>
          </AuthProvider>
        <ToastContainer
            position="bottom-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss={false}
            draggable={false}
            pauseOnHover={false}
            theme="dark"
            transition={Slide}
            />
      </body>
    </html>
  );
}
